---
- name: "Update all packages via dnf"
  dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: "Install basic utilities"
  dnf:
    name:
      - curl
      - tar
      - cronie
      - wget
      - net-tools
      - bind-utils
      - git
      - vim
    state: present

- name: "Ensure crond is started and enabled"
  service:
    name: crond
    state: restarted
    enabled: yes

- name: "Prepare DDNS Directory"
  become: "yes"
  file:
    path: "/opt/ddns"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"

- name: "Set Update DDNS Script."
  become: "yes"
  template:
    src: "update_ddns.sh.j2"
    dest: "/opt/ddns/update_ddns.sh"
    owner: "root"
    group: "root"
    mode: "0700"

- name: "Set Update DDNS Crontab"
  become: "yes"
  cron:
    name: "Update DDNS"
    backup: "No"
    cron_file: "/etc/cron.d/update_ddns"
    minute: "15"
    user: "root"
    job: "bash /opt/ddns/update_ddns.sh 2>&1 | logger -t UPDATE_DDNS"
    state: "present"
