---
- name: "Create Application Directory"
  file:
    path: "{{ app_dir }}"
    state: directory
    mode: '0755'

- name: "Deploy docker-compose.yml"
  template:
    src: docker-compose.yml.j2
    dest: "{{ app_dir }}/docker-compose.yml"
    mode: '0644'

- name: "Copy Caddyfile template"
  template:
    src: Caddyfile.j2
    dest: "{{ app_dir }}/Caddyfile"
    mode: '0644'
  notify: Restart caddy container 

- name: "Run docker compose up"
  community.docker.docker_compose_v2:
    project_src: "{{ app_dir }}"
    files:
      - docker-compose.yml
    state: present
  # ansible_check_mode が true（--check時）ならブロック全体をスキップ
  when: not ansible_check_mode